### ISSUE TITLE
Keys are shortened after tapply

### ISSUE THREAD

**Issue by balta2ar** [IRkernel/IRkernel#304]
When keys in the resulting table are long strings (factors?), they get shortened like this:
![shortened keys](http://scrin.org/i/16/04/tmpdopedjurlzs.png)

This is not the case in plain R console. How do I disable that shortening?

**Comment by flying-sheep** [comment]
it’s just visual. you can change it via CSS

```r
IRdisplay::display_html('<style>.dl-horizontal dt { width: 300px }</style>')
```

**Comment by balta2ar** [comment]
Thanks! Is there a way to make the first column as wide as needed to display the longest key? If I set `width: 100%`, the first column gets stretched horizontally across whole `<dl class="dl-horizontal">`. `width: auto` doesn't help either.

**Comment by flying-sheep** [comment]
well, you could try:

```css
.dl-horizontal { display:table }
.dl-horizontal dt,
.dl-horizontal dd { display: table-cell; width: auto }
```
